export 'package:flutter/material.dart';
export 'dart:io';
export 'package:equatable/equatable.dart';
export 'dart:convert';
export '../../constans/app_colors.dart';
export 'package:get/get.dart' hide HeaderValue;
export 'package:provider/provider.dart';
export 'package:gap/gap.dart';
export 'package:nima_ovqat/constans/local_images.dart';
export 'package:nima_ovqat/core/widgets/app_button.dart';
export 'package:nima_ovqat/router/router_name.dart';
export 'package:nima_ovqat/features/onboarding/presentation/onboarding_page.dart';
export 'package:nima_ovqat/constans/imports.dart';
export 'package:nima_ovqat/features/home/presentation/page/home_page.dart';
export 'package:flutter/cupertino.dart' hide RefreshCallback;
export 'package:nima_ovqat/core/theme/app_theme.dart';
export 'package:dio/dio.dart' hide FormData, Response, MultipartFile;
export 'package:flutter/services.dart';
export 'package:get_storage/get_storage.dart';
export 'package:nima_ovqat/router/app_name.dart';
export '../../../injector_container.dart';
export 'package:nima_ovqat/features/home/presentation/widgets/custom_search_delegate.dart';
export 'package:nima_ovqat/features/home/presentation/widgets/recipes.dart';
export 'package:nima_ovqat/features/home/presentation/widgets/%D1%81ategory_button.dart';
export 'package:nima_ovqat/features/home/presentation/widgets/custom_search_container.dart';
export 'package:video_player/video_player.dart';
export 'package:nima_ovqat/features/home/presentation/widgets/Recipes_date_item.dart';
export 'package:nima_ovqat/core/utils/api_servis.dart';
export 'package:nima_ovqat/features/home/data/models/category_model.dart';
export 'package:nima_ovqat/features/home/logic/categories_provider.dart';
export 'package:nima_ovqat/features/home/logic/home_provader.dart';
export 'package:nima_ovqat/features/home/presentation/widgets/categories_details_widget.dart';
export 'package:nima_ovqat/features/home/presentation/page/recipes_card.dart';
export 'package:nima_ovqat/features/splash/presentation/pages/splash_page.dart';

